language: php

services:
  - mysql

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_install:
  - mysql -e "CREATE DATABASE test;CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost';FLUSH PRIVILEGES;"

install:
  - composer install

script:
  - vendor/bin/phpunit test